version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: sam
  coins:
  - 10000token 
  - 1000000stake
  mnemonic: demise mistake strategy immune dog mimic ranch roast cruise sauce matter novel
faucet:
  name: bob
  coins:
  - 10000token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
