// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitid/did/your_messages.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgDefineDIDDocument represents a request to create/update a DID document.
type MsgDefineDIDDocument struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Document string `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
}

func (m *MsgDefineDIDDocument) Reset()         { *m = MsgDefineDIDDocument{} }
func (m *MsgDefineDIDDocument) String() string { return proto.CompactTextString(m) }
func (*MsgDefineDIDDocument) ProtoMessage()    {}
func (*MsgDefineDIDDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e580b84691802b, []int{0}
}
func (m *MsgDefineDIDDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDefineDIDDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDefineDIDDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDefineDIDDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDefineDIDDocument.Merge(m, src)
}
func (m *MsgDefineDIDDocument) XXX_Size() int {
	return m.Size()
}
func (m *MsgDefineDIDDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDefineDIDDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDefineDIDDocument proto.InternalMessageInfo

func (m *MsgDefineDIDDocument) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDefineDIDDocument) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgDefineDIDDocument) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

type MsgDefineDIDDocumentResponse struct {
	// Define any fields you want to include in the response
	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgDefineDIDDocumentResponse) Reset()         { *m = MsgDefineDIDDocumentResponse{} }
func (m *MsgDefineDIDDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDefineDIDDocumentResponse) ProtoMessage()    {}
func (*MsgDefineDIDDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e580b84691802b, []int{1}
}
func (m *MsgDefineDIDDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDefineDIDDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDefineDIDDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDefineDIDDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDefineDIDDocumentResponse.Merge(m, src)
}
func (m *MsgDefineDIDDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDefineDIDDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDefineDIDDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDefineDIDDocumentResponse proto.InternalMessageInfo

func (m *MsgDefineDIDDocumentResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

// MsgRemoveDIDDocument represents a request to remove a DID document.
type MsgRemoveDIDDocument struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRemoveDIDDocument) Reset()         { *m = MsgRemoveDIDDocument{} }
func (m *MsgRemoveDIDDocument) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDIDDocument) ProtoMessage()    {}
func (*MsgRemoveDIDDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e580b84691802b, []int{2}
}
func (m *MsgRemoveDIDDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDIDDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDIDDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDIDDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDIDDocument.Merge(m, src)
}
func (m *MsgRemoveDIDDocument) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDIDDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDIDDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDIDDocument proto.InternalMessageInfo

func (m *MsgRemoveDIDDocument) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemoveDIDDocument) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgRemoveDIDDocumentResponse struct {
	// Define any fields you want to include in the response
	Remover string `protobuf:"bytes,1,opt,name=remover,proto3" json:"remover,omitempty"`
}

func (m *MsgRemoveDIDDocumentResponse) Reset()         { *m = MsgRemoveDIDDocumentResponse{} }
func (m *MsgRemoveDIDDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDIDDocumentResponse) ProtoMessage()    {}
func (*MsgRemoveDIDDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e580b84691802b, []int{3}
}
func (m *MsgRemoveDIDDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDIDDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDIDDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDIDDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDIDDocumentResponse.Merge(m, src)
}
func (m *MsgRemoveDIDDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDIDDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDIDDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDIDDocumentResponse proto.InternalMessageInfo

func (m *MsgRemoveDIDDocumentResponse) GetRemover() string {
	if m != nil {
		return m.Remover
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgDefineDIDDocument)(nil), "bitid.did.MsgDefineDIDDocument")
	proto.RegisterType((*MsgDefineDIDDocumentResponse)(nil), "bitid.did.MsgDefineDIDDocumentResponse")
	proto.RegisterType((*MsgRemoveDIDDocument)(nil), "bitid.did.MsgRemoveDIDDocument")
	proto.RegisterType((*MsgRemoveDIDDocumentResponse)(nil), "bitid.did.MsgRemoveDIDDocumentResponse")
}

func init() { proto.RegisterFile("bitid/did/your_messages.proto", fileDescriptor_48e580b84691802b) }

var fileDescriptor_48e580b84691802b = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xaf, 0x15, 0xd4, 0xcb, 0x20, 0x58, 0x6e, 0x28, 0x45, 0x83, 0x74, 0xd2, 0xa5, 0x19,
	0x5c, 0x1c, 0xe5, 0xec, 0x72, 0x83, 0x4b, 0xdd, 0x44, 0x90, 0xb6, 0x79, 0xd6, 0x80, 0xe9, 0x2b,
	0x79, 0x89, 0x78, 0xff, 0x85, 0x7f, 0x96, 0xe3, 0x8d, 0x8e, 0xd2, 0xfe, 0x23, 0x72, 0xb9, 0xde,
	0x21, 0xe8, 0xe4, 0x12, 0xde, 0xf7, 0x7d, 0xe4, 0xfb, 0x3d, 0x12, 0x76, 0x5a, 0x29, 0xab, 0xa4,
	0x90, 0x4a, 0x8a, 0x25, 0x3a, 0xf3, 0xa8, 0x81, 0xa8, 0x6c, 0x80, 0xb2, 0xce, 0xa0, 0xc5, 0x68,
	0xea, 0xe3, 0x4c, 0x2a, 0x99, 0x1c, 0x97, 0x5a, 0xb5, 0x28, 0xfc, 0xb9, 0x49, 0x93, 0x59, 0x83,
	0x0d, 0xfa, 0x51, 0xac, 0xa7, 0x8d, 0x9b, 0x3e, 0xb0, 0xd9, 0x2d, 0x35, 0x39, 0x3c, 0xa9, 0x16,
	0xf2, 0x45, 0x9e, 0x63, 0xed, 0x34, 0xb4, 0x36, 0x8a, 0xd9, 0x41, 0x6d, 0xa0, 0xb4, 0x68, 0xe2,
	0xe0, 0x2c, 0x38, 0x9f, 0x16, 0x5b, 0x19, 0x1d, 0xb1, 0x50, 0xc9, 0x38, 0xf4, 0x66, 0xa8, 0x64,
	0x94, 0xb0, 0x43, 0x39, 0xde, 0x8a, 0xf7, 0xbc, 0xbb, 0xd3, 0xe9, 0x15, 0x3b, 0xf9, 0xab, 0xbd,
	0x00, 0xea, 0xb0, 0x25, 0x58, 0x53, 0xc8, 0xd5, 0x35, 0x10, 0x6d, 0x29, 0xa3, 0x4c, 0xaf, 0xfd,
	0x5e, 0x05, 0x68, 0x7c, 0xfd, 0xdf, 0x5e, 0x23, 0xfb, 0x57, 0xc3, 0x4f, 0xb6, 0xf1, 0xe1, 0xae,
	0x69, 0x94, 0xf3, 0x9b, 0x8f, 0x9e, 0x07, 0xab, 0x9e, 0x07, 0x5f, 0x3d, 0x0f, 0xde, 0x07, 0x3e,
	0x59, 0x0d, 0x7c, 0xf2, 0x39, 0xf0, 0xc9, 0xfd, 0x45, 0xa3, 0xec, 0xb3, 0xab, 0xb2, 0x1a, 0xb5,
	0xb8, 0x2b, 0xb5, 0x83, 0x97, 0x02, 0x40, 0x82, 0x11, 0x73, 0x65, 0x17, 0xb9, 0x78, 0xf3, 0x5f,
	0x63, 0x97, 0x1d, 0x50, 0xb5, 0xef, 0xdf, 0xf7, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x28,
	0x37, 0x0c, 0xb4, 0x01, 0x00, 0x00,
}

func (m *MsgDefineDIDDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDefineDIDDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDefineDIDDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Document) > 0 {
		i -= len(m.Document)
		copy(dAtA[i:], m.Document)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Document)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDefineDIDDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDefineDIDDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDefineDIDDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Success) > 0 {
		i -= len(m.Success)
		copy(dAtA[i:], m.Success)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Success)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDIDDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDIDDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDIDDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDIDDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDIDDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDIDDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Remover) > 0 {
		i -= len(m.Remover)
		copy(dAtA[i:], m.Remover)
		i = encodeVarintYourMessages(dAtA, i, uint64(len(m.Remover)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintYourMessages(dAtA []byte, offset int, v uint64) int {
	offset -= sovYourMessages(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDefineDIDDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	l = len(m.Document)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	return n
}

func (m *MsgDefineDIDDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Success)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	return n
}

func (m *MsgRemoveDIDDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	return n
}

func (m *MsgRemoveDIDDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Remover)
	if l > 0 {
		n += 1 + l + sovYourMessages(uint64(l))
	}
	return n
}

func sovYourMessages(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozYourMessages(x uint64) (n int) {
	return sovYourMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDefineDIDDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYourMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDefineDIDDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDefineDIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Document", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Document = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYourMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthYourMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDefineDIDDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYourMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDefineDIDDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDefineDIDDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Success = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYourMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthYourMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDIDDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYourMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDIDDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYourMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthYourMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDIDDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYourMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDIDDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDIDDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remover", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYourMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthYourMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Remover = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYourMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthYourMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipYourMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowYourMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYourMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthYourMessages
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupYourMessages
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthYourMessages
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthYourMessages        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowYourMessages          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupYourMessages = fmt.Errorf("proto: unexpected end of group")
)
