swagger: '2.0'
info:
  title: HTTP API Console bitid.did
  name: ''
  description: ''
paths:
  /SamuelReeder/BitID/did/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  DIDDocument:
    type: object
    properties:
      context:
        type: string
      id:
        type: string
      authentication:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            controller:
              type: string
            publicKeyPem:
              type: string
      service:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            serviceEndpoint:
              type: string
      created:
        type: string
      updated:
        type: string
  Params:
    type: object
  QueryGetDIDResponse:
    type: object
    properties:
      DID:
        type: object
        properties:
          context:
            type: string
          id:
            type: string
          authentication:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                controller:
                  type: string
                publicKeyPem:
                  type: string
          service:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                serviceEndpoint:
                  type: string
          created:
            type: string
          updated:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  Service:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      serviceEndpoint:
        type: string
  VerificationMethod:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      controller:
        type: string
      publicKeyPem:
        type: string
  MsgDefineDIDDocumentResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
